
development:  
  adapter: postgresql
  encoding: unicode
  database: tiny-library-dev
  pool: 5
  username: adamwatters
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: tiny-library-test
  pool: 5
  username: adamwatters
  password:
